"""Generate the manuscript's LaTeX tables, the scenario-card appendix and paper/sections/numbers.tex from the outputs.

Run after the pipeline and the figures (`make tables`). Every number quoted in the manuscript text is a macro defined in
numbers.tex; a missing input stops the script (set ALLOW_MISSING=1 only for partial development runs, in which case the
affected sections are skipped and the manuscript will not compile). Inputs:
  outputs/scenarios/S*.json, outputs/scenarios/synthetic_horizons.npz
  outputs/tables/{scenario_summary,strategy_objectives,strategy_nondominance,opportunity_window_probability,
      opportunity_probability_vs_duration,opportunity_statistics,opportunity_convergence,reachability_convergence,
      timeline_window_probability,reachability_region_summary,timeline_families,refined_windows,convergence,
      observing_windows_calendar,daily_availability,facility_site_time_matrix,plume_convergence}.csv
  outputs/tables/{injection_recovery,peak_magnitude_distribution,ejecta_checks,orbiter_seasons}.json
  outputs/validation/{ephemeris_validation,iers_provenance,lightcurve_accuracy,transfer_check}.json, outputs/screening/{maps,classes}.npz
  research/orbiter_latency.csv, config/*.yaml
"""
import sys, os, json, glob, yaml, numpy as np, pandas as pd
root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
os.makedirs(os.path.join(root, 'paper', 'sections'), exist_ok=True)
sys.path.insert(0, root)
from ayap1obs import impact as I, detect as D, montecarlo as MC, reachability as R, opportunities as OP
ALLOW_MISSING = os.environ.get('ALLOW_MISSING') == '1'
SEC = f'{root}/paper/sections'

def need(rel):
    p = f'{root}/{rel}'
    if os.path.exists(p):
        return p
    if ALLOW_MISSING:
        print(f'WARNING: {rel} missing; dependent sections skipped')
        return None
    raise FileNotFoundError(f'{rel} is required by make_tables.py (run the pipeline first)')

def tex(s):
    rep = [('\\', '\\textbackslash{}'), ('&', '\\&'), ('%', '\\%'), ('_', '\\_'), ('#', '\\#'), ('~', '$\\sim$'), ('^', '\\^{}'),
           ('+-', '$\\pm$'), ('ü', '\\"u'), ('Ü', '\\"U'), ('ö', '\\"o'), ('Ö', '\\"O'), ('ş', '\\c{s}'), ('Ş', '\\c{S}'), ('ğ', '\\u{g}'),
           ('ı', '{\\i}'), ('İ', '\\.{I}'), ('ç', '\\c{c}'), ('Ç', '\\c{C}'), ('≥', '$\\geq$'), ('≤', '$\\leq$'), ('°', '$^\\circ$'), ('–', '--')]
    s = str(s)
    for a, b in rep:
        s = s.replace(a, b)
    return s

def fp(x, nd=2):
    """Probability for tables and text: two decimals; values below 0.005 (but non-zero) as '<0.01'."""
    if x is None or (isinstance(x, float) and not np.isfinite(x)):
        return '--'
    if x == 0:
        return '0'
    if 0 < x < 0.005:
        return '$<$0.01'
    return f'{x:.{nd}f}'

def fsmall(x):
    """Small probabilities (visual witnessing): '<0.0001' below 1e-4, else 4 decimals below 0.01, else 2 decimals."""
    if x is None or not np.isfinite(x):
        return '--'
    if x < 1e-4:
        return '$<$0.0001'
    if x < 0.01:
        return f'{x:.4f}'
    return f'{x:.2f}'

def sci(x, nd=1):
    m, e = f'{x:.{nd}e}'.split('e')
    return f'{m}\\times10^{{{int(e)}}}'

def thou(n):
    return f'{int(round(n)):,}'.replace(',', '\\,')

NUM = ['% Auto-generated by scripts/make_tables.py from outputs/ -- do not edit by hand.']
DEFINED = set()
def nm(name, val, fmt='{:.2f}'):
    assert name.isalpha(), f'macro name must be letters only: {name}'
    assert name not in DEFINED, f'macro defined twice: {name}'
    DEFINED.add(name)
    NUM.append(f'\\newcommand{{\\N{name}}}{{{val if isinstance(val, str) else fmt.format(val)}}}')

KG = lambda v: f'{v:.0f}' if v < 9999.5 else f'{v:,.0f}'.replace(',', '\\,')            # 4105, 189\,152 (thin space from five digits)
W = {'S1': 'One', 'S2': 'Two', 'S3': 'Three', 'S4': 'Four', 'S5': 'Five', 'S6': 'Six', 'S7': 'Seven', 'S8': 'Eight', 'S9': 'Nine', 'S10': 'Ten', 'S11': 'Eleven'}
SL = {'A_turkiye_priority': 'A', 'B_global_science': 'B', 'C_public_participation': 'C'}
OUT = {'any': 'any', 'two_indep': 'two', 'dual_validated': 'dual', 'confirmed': 'conf', 'obvious_any': 'obv', 'live': 'live', 'rapid': 'rapid', 'turkish': 'tr'}
PRIOR = 'wide|broad'; PRIOR_V = 'v-scaled|broad'

cfg = yaml.safe_load(open(f'{root}/config/scenarios.yaml')); sites_cfg = {s['id']: s for s in yaml.safe_load(open(f'{root}/config/sites.yaml'))['sites']}
fam = yaml.safe_load(open(f'{root}/config/orbit_families.yaml')); dom = yaml.safe_load(open(f'{root}/config/domain.yaml'))
orbcfg = yaml.safe_load(open(f'{root}/config/orbiters.yaml'))
templates = MC.load_templates()
cards = {os.path.basename(f)[:-5]: json.load(open(f)) for f in sorted(glob.glob(f'{root}/outputs/scenarios/S*.json'))}
order = [s['id'] for s in cfg['scenarios'] if s['id'] in cards]
if len(order) != len(cfg['scenarios']) and not ALLOW_MISSING:
    raise FileNotFoundError(f'scenario cards missing: {sorted(set(s["id"] for s in cfg["scenarios"]) - set(order))}')
scn_cfg = {s['id']: s for s in cfg['scenarios']}
def mcs(sid, strat, out, prior=PRIOR):
    return cards[sid]['mc'][prior]['strategies'][strat][out]

# =====================================================================================================================
# TABLES
# =====================================================================================================================
# ---- scenario geometry and context (landscape)
L = [r'\begin{landscape}', r'\begin{table}', r'\centering',
     r'\caption{Scenario geometry and context (all HYPOTHETICAL test points; impact time = emission time at the lunar surface). $e$, $i$: geocentric emission and solar incidence angles; illum: illuminated fraction; sites: configured sites available (Moon $\geq20^\circ$, Sun $\leq-12^\circ$, point visible, not seasonally closed; T\"urkiye in brackets); $P_{\rm plane}$: fraction of uniformly distributed polar planes within 0.6$^\circ$/2.5$^\circ$ of a plane through the point at the epoch; $p_{\rm terr}$: terrain-visibility range over the three synthetic relief levels; pop: sum of GeoNames settlement populations under the public criteria with 10-km agglomeration (range over 0--25 km), not a census or audience; $V_{\rm pk}$: median predicted peak $V$ (10--90\%, wide prior); rim: crater rim-diameter envelope (both oblique-impact rules); plume: status of the within-domain plume estimate.}',
     r'\label{tab:scenarios}', r'\scriptsize', r'\setlength{\tabcolsep}{2.4pt}',
     r'\begin{tabular}{@{}lllrrlrrrlllllp{3.4cm}@{}}', r'\toprule',
     r'Id & Class & (lat, lon) & $e$ & $i$ & impact UTC (Istanbul) & illum & sites & $P_{\rm plane}$ & $p_{\rm terr}$ & pop (bn) & $V_{\rm pk}$ & rim (m) & & plume \\', r'\midrule']
def plume_status(c):
    cs = c['plume']['cases']
    det = [x for x in cs if x.get('observers')]
    if not det:
        return 'cannot determine (all cases)' if c['plume'].get('emission_criterion_ok', True) else 'no visible plume geometry'
    snr = max(max(v['sys0.001']['snr_max'] for v in x['observers'].values() if isinstance(v, dict) and 'sys0.001' in v) for x in det)
    return f'{len(det)}/{len(cs)} cases estimable; max SNR {snr:.2f}' if snr < 1 else f'{len(det)}/{len(cs)} cases estimable; max SNR {snr:.1f}'
for sid in order:
    c = cards[sid]; g = c['geometry']; rc = c['reachability']; pr = c['population']['by_radius']
    pk = c['mc'][PRIOR]['peakV']; rim = c['crater']['rim_diameter_m']['all']
    pp = rc.get('p_random_polar_plane_within', {}) if rc.get('status') == 'conditional' else {}
    pplane = f"{pp['0.6']:.3f}/{pp['2.5']:.3f}" if pp else '--'
    terr = c['terrain']['p_terrain_range']
    L.append(f"{sid} & {tex(c['cls'])} & ({c['lat']:+.0f}, {c['lon']:+.0f}) & {g['emission_geocentric']:.0f} & {g['incidence']:.0f} & {c['impact_utc'][:16].replace('T', ' ')} ({c['epoch_istanbul'][11:16]}) & "
             f"{c['moon']['illum_frac']:.2f} & {c['n_sites_available']} ({len(c['turkish_sites_available'])}) & {pplane} & {terr[0]:.2f}--{terr[1]:.2f} & "
             f"{pr['10km']['public'] / 1e9:.2f} ({pr['25km']['public'] / 1e9:.2f}--{pr['0km']['public'] / 1e9:.2f}) & {pk['median']:.1f} ({pk['p10']:.1f}--{pk['p90']:.1f}) & {rim[0]:.0f}--{rim[2]:.0f} & & {tex(plume_status(c))} \\\\")
L += [r'\bottomrule', r'\end{tabular}', r'\end{table}', r'\end{landscape}']
open(f'{SEC}/tab_scenarios.tex', 'w').write('\n'.join(L))

# ---- network probabilities with uncertainty (landscape)
def pr3(sid, strat, out, prior=PRIOR):
    m = mcs(sid, strat, out, prior)
    return f"{fp(m['p'])} ({fp(m['outer_p05'])}--{fp(m['outer_p95'])})"
L = [r'\begin{landscape}', r'\begin{table}', r'\centering',
     r'\caption{Network outcome probabilities per scenario and strategy, conditional on the spacecraft reaching the stated terminal state (wide $\eta_{\rm vis}$ prior, broad $T_0$ prior; $N=\NnEvents$ events in $\NnOuter$ outer draws). Each entry is the pooled probability and, in brackets, the 5--95\% range of the conditional probability over the outer (epistemic) draws after removing the binomial noise of the \NnInner{} inner events per draw (beta-binomial deconvolution, Section~\ref{sec:mc}); the 95\% Monte Carlo interval of every pooled value is narrower than $\pm$\NmcHalfMax. Two sites: detections at stations more than 100~km apart; confirmed: two sites or a dual-camera validation; live: obvious ($\geq$30) at a streaming station; $v$-scaled: the speed-scaled prior.}',
     r'\label{tab:probabilities}', r'\scriptsize', r'\setlength{\tabcolsep}{3pt}',
     r'\begin{tabular}{@{}llllllllll@{}}', r'\toprule',
     r' & \multicolumn{3}{c}{P(at least one detection)} & \multicolumn{3}{c}{P(two sites)} & P(confirmed) & P(live) & P(any) \\',
     r'\cmidrule(lr){2-4}\cmidrule(lr){5-7}',
     r'Id & A (T\"urkiye) & B (global) & C (public) & A & B & C & B & C & B, $v$-scaled \\', r'\midrule']
for sid in order:
    L.append(f"{sid} & " + ' & '.join([pr3(sid, s, 'any') for s in SL] + [pr3(sid, s, 'two_indep') for s in SL] +
                                    [pr3(sid, 'B_global_science', 'confirmed'), pr3(sid, 'C_public_participation', 'live'), pr3(sid, 'B_global_science', 'any', PRIOR_V)]) + r' \\')
L += [r'\bottomrule', r'\end{tabular}', r'\end{table}', r'\end{landscape}']
open(f'{SEC}/tab_probabilities.tex', 'w').write('\n'.join(L))

# ---- strategy objectives (S1, S11, S3, S4)
so_all = pd.read_csv(need('outputs/tables/strategy_objectives.csv')); so = so_all[so_all.prior == PRIOR]
nd = pd.read_csv(need('outputs/tables/strategy_nondominance.csv'))
ndk = {(r.scenario, r.strategy): bool(r.nondominated) for r in nd.itertuples()}
ndc = {(r.scenario, r.strategy): bool(r.nondominated_conservative) for r in nd.itertuples()}
L = [r'\begin{table}[t]', r'\centering',
     r'\caption{Strategy objectives for four scenarios (wide prior; pooled probabilities, outer 5--95\% ranges in Table~\ref{tab:probabilities}). Stations: recruited / available at the epoch; weight: illustrative relative resource weight summed over recruited (available) stations, dimensionless and not telescope time; ND: nondominated within the scenario across P(two sites), P(live), P(T\"urkiye) and the recruited weight; first entry descriptive (point estimates), second conservative (a strategy is dominated only if another is at least as good on every objective and significantly better on one, paired intervals with a Bonferroni correction over the three probabilities).}',
     r'\label{tab:strategies}', r'\footnotesize', r'\setlength{\tabcolsep}{3.5pt}',
     r'\begin{tabular}{@{}llrrrrrrrrl@{}}', r'\toprule',
     r'Scen. & Strategy & stations & weight & P(any) & P(two) & P(dual) & P(conf) & P(live) & P(TR) & ND \\', r'\midrule']
for sid in ['S1', 'S11', 'S3', 'S4']:
    for strat, S in SL.items():
        r = so[(so.scenario == sid) & (so.strategy == strat)].iloc[0]
        L.append(f"{sid} & {S} & {r.n_stations}/{r.n_available} & {r.weight_recruited:.1f} ({r.weight_available:.1f}) & {fp(r.p_any)} & {fp(r.p_two_indep)} & {fp(r.p_dual_validated)} & {fp(r.p_confirmed)} & {fp(r.p_live)} & {fp(r.p_turkish)} & {'yes' if ndk.get((sid, strat)) else 'no'}/{'yes' if ndc.get((sid, strat)) else 'no'} \\\\")
    if sid != 'S4':
        L.append(r'\addlinespace[2pt]')
L += [r'\bottomrule', r'\end{tabular}', r'\end{table}']
open(f'{SEC}/tab_strategies.tex', 'w').write('\n'.join(L))

# ---- opportunity (terminal-window) probabilities
CLS = {'A_turkiye_evening_public': 'A', 'B_global_science': 'B', 'C_any_turkish': 'C', 'P_plume_global': 'P'}
wp = pd.read_csv(need('outputs/tables/opportunity_window_probability.csv'))
po = pd.read_csv(need('outputs/tables/opportunity_probability_vs_duration.csv'))
ost = pd.read_csv(need('outputs/tables/opportunity_statistics.csv'))
def wstat(cls, dl, Wd, stat):
    x = wp[(wp.cls == cls) & (np.isclose(wp.delta, dl)) & (wp.W_days == Wd)].p
    return float({'mean': x.mean(), 'min': x.min(), 'max': x.max(), 'half': np.mean(x >= 0.5)}[stat])
def fstart(cls, dl, N):
    return float(po[(po.cls == cls) & (np.isclose(po.delta, dl)) & (po.months == N)].p_at_least_one.values[0])
def lun(cls, dl):
    x = ost[(ost.cls == cls) & (np.isclose(ost.delta, dl))]
    return x.n_lunations_with_opp, int(x.n_lunations.max())
L = [r'\begin{table}[t]', r'\centering',
     r'\caption{Terminal-window opportunity statistics for an unknown orbit plane and phase (72 directed polar planes, i.e. 36 node longitudes $\times$ 2 traversal directions, $\times$ 8 phases, uniform prior; circular-overflight screening opportunities with the impact placed \NtrOffset~s before the overflight for the 25-m/s de-orbit burn; \protect\path{outputs/tables/opportunity_window_probability.csv}). $P_W$: probability of at least one opportunity of the class within a window of $W$ days, given as the mean and the minimum over all start days in the domain; lunations: range over planes and phases of the number of lunations (of \NnLun) with at least one opportunity; fixed start: probability of a first opportunity within 3/6/12 months of 2027-09-01 (release-1 statistic, for comparison). Classes: A T\"urkiye evening, public phase, waxing, central near side, $\geq$3 sites; B central near side, $\geq$3 sites; C central near side, $\geq$1 Turkish site; P sunlit-plume geometry, $\geq$3 sites. $\delta$: cross-track allowance (0.6$^\circ\approx$\NdvSix~m/s, 2.5$^\circ\approx$\NdvTwoFive~m/s).}',
     r'\label{tab:opportunity}', r'\footnotesize', r'\setlength{\tabcolsep}{4pt}',
     r'\begin{tabular}{@{}llrrrrrrl@{}}', r'\toprule',
     r'Class & $\delta$ & $P_{30}$ mean & $P_{30}$ min & $P_{60}$ mean & $P_{60}$ min & $P_{90}$ min & lunations & fixed start 3/6/12 mo \\', r'\midrule']
for cls, C_ in CLS.items():
    for dl in fam['cross_track_tolerance_deg']:
        nl, nlt = lun(cls, dl)
        L.append(f"{C_} & {dl:g}$^\\circ$ & {wstat(cls, dl, 30, 'mean'):.2f} & {wstat(cls, dl, 30, 'min'):.2f} & {wstat(cls, dl, 60, 'mean'):.2f} & {wstat(cls, dl, 60, 'min'):.2f} & {wstat(cls, dl, 90, 'min'):.2f} & "
                 f"{nl.min()}--{nl.max()} & {fstart(cls, dl, 3):.2f}/{fstart(cls, dl, 6):.2f}/{fstart(cls, dl, 12):.2f} \\\\")
L += [r'\bottomrule', r'\end{tabular}', r'\end{table}']
open(f'{SEC}/tab_opportunity.tex', 'w').write('\n'.join(L))

# ---- admissible overflights per pixel by region
rrs = pd.read_csv(need('outputs/tables/reachability_region_summary.csv'))
REG = ['near side central', 'eastern limb region', 'western limb region', 'northern high latitude', 'southern high latitude', 'polar', 'far side']
def rreg(dl, q, reg, col='mean_opportunities'):
    return float(rrs[(np.isclose(rrs.delta, dl)) & (rrs.quantity == q) & (rrs.region == reg)][col].values[0])
L = [r'\begin{table}[t]', r'\centering',
     r'\caption{Circular-overflight screening opportunities per pixel over the domain, averaged over the 72 directed planes, the 8 phases and the pixels of each region (station and class gates evaluated at the impact time of each opportunity). flash\_cov3: flash geometry with $\geq$3 sites available; flash\_tr: flash geometry with $\geq$1 Turkish site; plume\_tr: sunlit-plume geometry with $\geq$1 Turkish site.}',
     r'\label{tab:reach_region}', r'\footnotesize', r'\begin{tabular}{@{}lrrrrrr@{}}', r'\toprule',
     r' & \multicolumn{3}{c}{$\delta=0.6^\circ$} & \multicolumn{3}{c}{$\delta=2.5^\circ$} \\', r'\cmidrule(lr){2-4}\cmidrule(lr){5-7}',
     r'Region & flash\_cov3 & flash\_tr & plume\_tr & flash\_cov3 & flash\_tr & plume\_tr \\', r'\midrule']
for reg in REG:
    L.append(f'{reg} & ' + ' & '.join(f'{rreg(dl, q, reg):.2f}' for dl in fam['cross_track_tolerance_deg'] for q in ['flash_cov3', 'flash_tr', 'plume_tr']) + r' \\')
L += [r'\bottomrule', r'\end{tabular}', r'\end{table}']
open(f'{SEC}/tab_reach.tex', 'w').write('\n'.join(L))

# ---- timeline families (nominal phase durations)
tf_all = pd.read_csv(need('outputs/tables/timeline_families.csv')); tf = tf_all[tf_all.phase_case == 'nominal']
L = [r'\begin{table}[t]', r'\centering',
     r'\caption{Launch-to-impact timeline families with nominal phase durations (SCENARIO ASSUMPTIONS spanning the published statements). Window opens: end of the science phase (the impact hour is set by the pass schedule); sessions: T\"urkiye evening observing sessions (illuminated fraction 0.12--0.5, Moon $>25^\circ$ at TUG, Sun $<-12^\circ$) within $\pm$15 days; best: the session with the most sites, Istanbul time; LRO: inside a computed LRO low-Sun season (orbit plane extrapolated from tracking data, Section~\ref{sec:orbiters_method}); $P_{30}$: probability of at least one opportunity of class A/B/P within 30 days after the window opens (unknown plane and phase, $\delta=0.6^\circ$; -- where the window extends beyond the domain).}',
     r'\label{tab:timeline}', r'\scriptsize', r'\setlength{\tabcolsep}{3pt}', r'\begin{tabular}{@{}llrllrlllll@{}}', r'\toprule',
     r'Launch & date & mo & science start & window opens & sessions & best session & LRO & $P_{30}$ A & $P_{30}$ B & $P_{30}$ P \\', r'\midrule']
def f30(x):
    return '--' if pd.isna(x) else f'{x:.2f}'
for _, r in tf.iterrows():
    best = str(r.best_session_istanbul).replace('T', ' ')[:16] if 'none' not in str(r.best_session_istanbul) else 'none'
    L.append(f"{r.launch} & {r.launch_date} & {r.science_months} & {r.science_start} & {r.impact_date} & {int(r.n_evening_sessions_pm15d) if pd.notna(r.n_evening_sessions_pm15d) else '--'} & {tex(best)} & {'yes' if r.in_LRO_low_sun_season else 'no'} & {f30(r.p30_A)} & {f30(r.p30_B)} & {f30(r.p30_P)} \\\\")
L += [r'\bottomrule', r'\end{tabular}', r'\end{table}']
open(f'{SEC}/tab_timeline.tex', 'w').write('\n'.join(L))

# ---- model flash magnitudes (ballistic case at 380 000 km)
Ek_bal = I.kinetic_energy(2000.0, 1.68); d38 = 3.8e8
def FM(eta, T0=2500.0, tau=0.5, Ek=Ek_bal):
    return I.FlashModel(Ek, eta, T0, float(I.floor_temperature(T0)), tau, tau)
L = [r'\begin{table}[t]', r'\centering',
     r"\caption{Model flash magnitudes for the ballistic case (2~t at 1.68~km/s, $E_k=2.8$~GJ) at 380\,000~km ($T_0=2500$~K, $\tau=0.5$~s, isotropic; generated by \texttt{make\_tables.py}). Peak: the maximum of the band light curve; ``33 ms'' and ``2 s'': exposure-averaged magnitudes for exposures starting at the onset; ``fluence'': the time-integrated band fluence as the magnitude of a 1-s source of equal fluence. Unocculted, above the atmosphere.}",
     r'\label{tab:magtable}', r'\footnotesize', r'\setlength{\tabcolsep}{4pt}', r'\begin{tabular}{@{}lrrrrrrrrrrr@{}}', r'\toprule',
     r'$\eta_{\rm vis}$ & $V$ peak & $R_c$ peak & $R_c$ 33 ms & $R_c$ fluence & $I_c$ peak & $I_c$ 33 ms & $J$ peak & $H$ peak & $K_s$ peak & $K_s$ 2 s & $K_s$ fluence \\', r'\midrule']
for e, lab in [(1e-3, '$10^{-3}$'), (1e-4, '$10^{-4}$'), (1e-5, '$10^{-5}$'), (1e-6, '$10^{-6}$')]:
    fm = FM(e)
    vals = [fm.peak_magnitude('V', d38), fm.peak_magnitude('Rc', d38), fm.exposure_averaged_magnitude('Rc', 0.033, distance_m=d38), fm.fluence('Rc', d38)[1], fm.peak_magnitude('Ic', d38),
            fm.exposure_averaged_magnitude('Ic', 0.033, distance_m=d38), fm.peak_magnitude('J', d38), fm.peak_magnitude('H', d38), fm.peak_magnitude('Ks', d38),
            fm.exposure_averaged_magnitude('Ks', 2.0, distance_m=d38), fm.fluence('Ks', d38)[1]]
    L.append(lab + ' & ' + ' & '.join(f'{v:.1f}' for v in vals) + r' \\')
L += [r'\bottomrule', r'\end{tabular}', r'\end{table}']
open(f'{SEC}/tab_magtable.tex', 'w').write('\n'.join(L))

# ---- injection-recovery
inj = json.load(open(need('outputs/tables/injection_recovery.json')))
INJ_TAG = {'nel': 'Nel', 'tug': 'Tug', 'ama': 'Ama', 'afo': 'Afo', 'std': 'Std'}
L = [r'\begin{table}[t]', r'\centering',
     r'\caption{Injection--recovery on synthetic lunar video (SIMULATION; \protect\path{outputs/tables/injection_recovery.json}). One detection pipeline serves injected and blank video. $m_{50}$, $m_{90}$: magnitudes recovered in 50\% and 90\% of trials (logistic fit, bootstrap 95\% intervals; \NinjNtrial{} trials per 0.25-mag step); analytic: steady-source SNR-8 limit of the aperture-sum estimator for the same background (not a matched-filter statistic); false alarms: candidates $\geq5\sigma$ per \NinjBox-pixel search box and frame in \NinjNclips{} independent blank clips of \NinjNseq{} frames, with clip-bootstrap 95\% intervals (a zero count gives a conditional one-sided limit); per window: expected false candidates in the frames searched for one injection. For the NELIOTA-like system the second row requires candidates in both cameras in the same frame. Magnitudes in the system band ($R_c$ for NELIOTA, broad for the others).}',
     r'\label{tab:injection}', r'\footnotesize', r'\setlength{\tabcolsep}{3pt}', r'\begin{tabular}{@{}p{4.3cm}lllll@{}}', r'\toprule',
     r'System & $m_{50}$ & $m_{90}$ & analytic & false alarms per box-frame & per window \\', r'\midrule']
def far(x):
    lo_, hi_ = x['ci95_clip_bootstrap']
    return f"{x['rate']:.4f} ({lo_:.4f}--{hi_:.4f})" if x['total'] > 0 else f"0 ($<${hi_:.4f})"
for key, tag in INJ_TAG.items():
    r = inj[key]; f0 = r['fits']['cam0']; fa = r['false_alarms']; c0 = fa['candidate_rate_per_box_frame'][0]
    L.append(f"{tex(r['label'])} & {f0['m50']:.2f} ({f0['m50_ci95'][0]:.2f}--{f0['m50_ci95'][1]:.2f}) & {f0['m90']:.2f} ({f0['m90_ci95'][0]:.2f}--{f0['m90_ci95'][1]:.2f}) & {r['analytic_limits']['steady_snr8']:.2f} & "
             f"{far(c0)} & {fa['expected_false_candidates_per_injection_window']:.2f} \\\\")
    if 'dual' in r['fits']:
        fd = r['fits']['dual']; dc = fa.get('dual_coincidence_rate_per_box_frame')
        L.append(f"\\quad both cameras, same frame & {fd['m50']:.2f} ({fd['m50_ci95'][0]:.2f}--{fd['m50_ci95'][1]:.2f}) & {fd['m90']:.2f} ({fd['m90_ci95'][0]:.2f}--{fd['m90_ci95'][1]:.2f}) & & "
                 + (far(dc) if dc else '--') + r' & \\')
L += [r'\bottomrule', r'\end{tabular}', r'\end{table}']
open(f'{SEC}/tab_injection.tex', 'w').write('\n'.join(L))

# ---- plume cases for the plume-relevant scenarios
L = [r'\begin{table}[t]', r'\centering',
     r"\caption{Phase-space plume model: within-domain estimates for scenarios S2 (3$^\circ$ beyond the terminator), S5 (sunlit ground) and S8 (polar, near the terminator), for every in-domain ejecta speed from the slowest that can be lit and seen. Rules: vertical-component ($U\sin\theta$) and vertical-equivalent ($U$); ``cannot determine'': the speed needed to reach sunlight (or to clear the limb) exceeds the scaling-domain maximum. SNR: exposure-integrated signal-to-noise ratio in the best 1-s window for a 1-m telescope ($V$) at TUG, regolith grains, $p\Phi=0.03$, dust/ground contrast $\kappa=0.2$, background-subtraction systematic $10^{-3}$ ($10^{-2}$ in brackets); fine: fine-rich grains; corner: fine-rich grains, $p\Phi=0.1$ and $\kappa=1$, the optimistic corner of the declared ranges; $M_{\rm vis}$: peak sunlit ejecta mass visible from TUG. Faster ejecta, outside the domain, are not modelled.}",
     r'\label{tab:plume}', r'\scriptsize', r'\setlength{\tabcolsep}{3pt}', r'\begin{tabular}{@{}lllllrrrr@{}}', r'\toprule',
     r'Scen. & rule & impactor & parameters & status & SNR & fine & corner & $M_{\rm vis}$ (kg) \\', r'\midrule']
for sid in ['S2', 'S5', 'S8']:
    for x in cards[sid]['plume']['cases']:
        ob = x.get('observers', {}).get('TUG')
        if ob:
            L.append(f"{sid} & {x['rule']} & {tex(x['impactor'])} & {tex(x['params'])} & within domain & {ob['sys0.001']['snr_max']:.2f} ({ob['sys0.01']['snr_max']:.2f}) & "
                     f"{ob['grains_sys0.001']['fine-rich']:.1f} & {ob['optimistic_corner_sys0.001']['snr_max']:.1f} & {KG(ob['M_vis_max_kg'])} \\\\")
        else:
            L.append(f"{sid} & {x['rule']} & {tex(x['impactor'])} & {tex(x['params'])} & cannot determine & -- & -- & -- & -- \\\\")
    if sid != 'S8':
        L.append(r'\addlinespace[2pt]')
L += [r'\bottomrule', r'\end{tabular}', r'\end{table}']
open(f'{SEC}/tab_plume.tex', 'w').write('\n'.join(L))

# =====================================================================================================================
# SCENARIO CARDS (appendix)
# =====================================================================================================================
B = [r'\section{Scenario cards}', r'\label{app:scenarios}',
     r"All coordinates are hypothetical test points chosen by the screening (latitude north-positive, longitude east-positive, ME frame); none is an official AYAP-1 target. The impact time is the emission time at the lunar surface; photons reach each station after its own light time. Reachability is conditional on the orbit plane and phase (Section~\ref{sec:reach}). Probabilities are conditional on reaching the stated terminal state; brackets give the 5--95\% range over the epistemic (outer) draws after removing the inner-sample binomial noise. ``Wide'' is the log-uniform $\eta_{\rm vis}$ prior and ``$v$-scaled'' the speed-scaled prior, both with the broad $T_0$ prior.", '']
def plim(x):
    return 'none (the background saturates the pixels)' if x is None or not np.isfinite(x) else f'{x:.1f}'
for sid in order:
    c = cards[sid]; sc = scn_cfg[sid]; g = c['geometry']; ph = c['physics']; rc = c['reachability']; pr = c['population']['by_radius']
    pB = lambda o, pri=PRIOR: mcs(sid, 'B_global_science', o, pri)
    def prr(strat, o, pri=PRIOR):
        m = mcs(sid, strat, o, pri); return f"{fp(m['p'])} ({fp(m['outer_p05'])}--{fp(m['outer_p95'])})"
    avail = c['sites_available']; tr = c['turkish_sites_available']; closed = c.get('sites_closed', [])
    lt = c['latency']['light_time_station_range_s'] or [c['latency']['light_time_geocentric_s']] * 2
    fl = {(round(x['eta_vis'], 9), x['T0']): x for x in c['flash_magnitudes']}
    def fl_txt(eta):
        x = fl.get((eta, 3000.0)) or next((v for k, v in fl.items() if k[0] == eta), None)
        return f"{x['V_peak']:.1f}/{x['Rc_peak']:.1f}/{x['Ic_peak']:.1f}/{x['Ks_peak']:.1f}" if x else '--'
    T0s = sorted(set(x['T0'] for x in c['flash_magnitudes']))
    reach_txt = (f"conditional on the orbit plane: planes through the point at the epoch have node longitude {rc['required_node_mod180_deg']:.1f}$^\\circ$ (mod 180$^\\circ$, at 2027-09-01); "
                 f"fraction of uniformly distributed polar planes within 0.6$^\\circ$ / 2.5$^\\circ$: {rc['p_random_polar_plane_within']['0.6']:.3f} / {rc['p_random_polar_plane_within']['2.5']:.3f} "
                 f"(plane change $\\approx${rc['plane_change_dv_m_s']['0.6']:.0f} / {rc['plane_change_dv_m_s']['2.5']:.0f} m/s); given the plane, the phase must also put the spacecraft over the point"
                 if rc.get('status') == 'conditional' else tex(rc.get('note', rc.get('status', ''))))
    pl_cases = c['plume']['cases']; det = [x for x in pl_cases if x.get('observers', {}).get('TUG')]
    if det:
        snr = [x['observers']['TUG']['sys0.001']['snr_max'] for x in det]; mv = [x['observers']['TUG']['M_vis_max_kg'] for x in det]
        fine = [x['observers']['TUG']['grains_sys0.001']['fine-rich'] for x in det]
        rg = lambda v, f: f(min(v)) if f(min(v)) == f(max(v)) else f'{f(min(v))}--{f(max(v))}'      # range, or one value if equal
        pl_txt = (f"{len(det)} of {len(pl_cases)} model cases estimable within the scaling domain: peak visible sunlit mass {rg(mv, KG)} kg, best exposure-integrated SNR "
                  f"{rg(snr, '{:.2f}'.format)} (1-m telescope, 1-s $V$ window, regolith grains, systematic $10^{{-3}}$; fine-rich grains {rg(fine, '{:.1f}'.format)})"
                  + ("; the others cannot be determined" if len(det) < len(pl_cases) else ""))
    else:
        pl_txt = f"all {len(pl_cases)} model cases: cannot determine (the speed needed to reach sunlight exceeds the scaling-domain maximum)" if pl_cases else 'no plume geometry'
    lro = c['orbiters']['lro']['low_sun_season'] or {}; dan = c['orbiters']['danuri']
    unc = ' (near an uncertain boundary)' if lro.get('boundary_uncertain') else ''
    lro_txt = (('inside a computed LRO low-Sun season (' + ' to '.join(lro['next_season']) + ')' + unc) if lro.get('inside') else
               (f"next computed LRO low-Sun season in {lro['days_until']} d ({' to '.join(lro['next_season'])}){unc}" if lro.get('next_season') else 'no season in the computed span'))
    dan_txt = ('Danuri available in the baseline (before its planned March 2028 impact), assumed availability ' + f"{dan['p_operational_assumed']}" if dan['available_in_baseline']
               else 'Danuri not available in the baseline (planned lunar impact in March 2028; continued operation is a changed-plan sensitivity)')
    rim = c['crater']['rim_diameter_m']
    vis = c['public']['visual']
    vis_txt = (f"at {vis['site']} (Moon {vis['moon_alt']:.0f}$^\\circ$, Sun {vis['sun_alt']:.0f}$^\\circ$), conditional on a clear, unobstructed, attentive view: naked eye {fsmall(vis['none']['p_conditional'])}, 7$\\times$50 binoculars {fsmall(vis['binoculars']['p_conditional'])}, 20-cm eyepiece {fsmall(vis['telescope20cm']['p_conditional'])} (with the site's weather: {fsmall(vis['telescope20cm']['p_with_weather'])})"
               if vis.get('observable') else f"the impact point is not observable from {vis['site']} under the public criteria")
    B += [r'\subsection*{' + tex(f"{sid}: {sc['name']}") + '}',
          r'\begin{tabularx}{\textwidth}{@{}p{3.5cm}X@{}}', r'\toprule',
          f"Class & {tex(c['cls'])}; physics case {tex(ph['label'])} ({tex(ph['status'])}) \\\\",
          f"Coordinates (hypothetical) & lat {c['lat']:+.1f}$^\\circ$, lon {c['lon']:+.1f}$^\\circ$E; region: {tex(c['region'])}; rationale: {tex(sc['rationale'])} \\\\",
          f"Impact time & {c['impact_utc'][:19].replace('T', ' ')} UTC = {c['impact_tdb'][:19].replace('T', ' ')} TDB = {tex(c['epoch_istanbul'])}; photons reach the stations {lt[0]:.3f}--{lt[1]:.3f} s later; Earth--Moon distance {c['moon']['distance_km']:.0f} km \\\\",
          f"Geometry (geocentric) & emission {g['emission_geocentric']:.1f}$^\\circ$, solar incidence {g['incidence']:.1f}$^\\circ$ ({'sunlit' if g['sunlit'] else 'dark'}); illuminated fraction {c['moon']['illum_frac']:.2f} ({'waxing' if c['moon']['waxing'] else 'waning'}); sub-Earth point ({c['moon']['subearth_lon']:+.1f}, {c['moon']['subearth_lat']:+.1f}); shadow-edge height {g['shadow_height_km']:.1f} km \\\\",
          f"Reachability & {reach_txt} \\\\",
          f"Terrain & {tex(c['terrain']['dem'])}; synthetic-relief sensitivity: P(Earth above the local horizon) {c['terrain']['p_terrain_range'][0]:.2f}--{c['terrain']['p_terrain_range'][1]:.2f} over the three relief levels (illustrative, not a validated prior) \\\\",
          f"Impact energy & $E_k$ = {c['energy']['E_k_J'] / 1e9:.2f} GJ ({c['energy']['tnt_equiv_kg']:.0f} kg TNT), mass {ph['mass_kg'][0]}--{ph['mass_kg'][1]} kg, $v$ = {ph['v_km_s']} km/s at {ph['angle_deg']}$^\\circ$ from horizontal \\\\",
          f"Available facilities & {len(avail)} configured sites ({len(tr)} Turkish): {tex(', '.join(avail)) if avail else 'none'}" + (f"; seasonally closed: {tex(', '.join(closed))}" if closed else '') + " \\\\",
          f"Predicted flash & peak $V/R_c/I_c/K_s$ at $T_0$ = 3000 K, $\\tau$ = 0.5 s: $\\eta_{{\\rm vis}}=10^{{-5}}$: {fl_txt(1e-5)}; $10^{{-4}}$: {fl_txt(1e-4)}; $10^{{-3}}$: {fl_txt(1e-3)}; Monte Carlo median peak $V$ {c['mc'][PRIOR]['peakV']['median']:.1f} (10--90\\%: {c['mc'][PRIOR]['peakV']['p10']:.1f}--{c['mc'][PRIOR]['peakV']['p90']:.1f}); laboratory-trend case $V\\approx${c['lab_trend']['V_peak']:.0f} \\\\",
          f"Requirements & fast ($\\leq$50 ms) visible or $\\geq$1-s near-infrared imaging with GPS timing; field covering the ellipse ($\\sigma$ along/cross {ph['sigma_along_km']}/{ph['sigma_cross_km']} km = {206265 * ph['sigma_along_km'] / c['moon']['distance_km']:.1f}$''$/{206265 * ph['sigma_cross_km'] / c['moon']['distance_km']:.1f}$''$); linear $\\geq$12-bit data; non-sidereal tracking; timing uncertainty $\\pm${ph['sigma_t_min']} min requires continuous recording \\\\",
          f"Network probabilities & P(any): A {prr('A_turkiye_priority', 'any')}, B {prr('B_global_science', 'any')}, C {prr('C_public_participation', 'any')}; P(two sites): A {prr('A_turkiye_priority', 'two_indep')}, B {prr('B_global_science', 'two_indep')}, C {prr('C_public_participation', 'two_indep')}; P(confirmed, B) {prr('B_global_science', 'confirmed')}; P(live, C) {prr('C_public_participation', 'live')}; P(T\\\"urkiye detection, A) {prr('A_turkiye_priority', 'turkish')}; $v$-scaled prior: P(any, B) {prr('B_global_science', 'any', PRIOR_V)} \\\\",
          f"Visual-threshold model & {vis_txt}; phone limits (broad band, steady source): standalone {plim(c['public']['phone_standalone_limit_broad'])}, afocal on 20 cm {plim(c['public']['phone_afocal20cm_limit_broad'])} \\\\",
          f"Settlement sums & GeoNames settlement populations under the public criteria: {pr['10km']['public'] / 1e9:.2f} bn (10-km agglomeration; {pr['25km']['public'] / 1e9:.2f}--{pr['0km']['public'] / 1e9:.2f} for 25--0 km), T\\\"urkiye {pr['10km']['turkiye_public'] / 1e6:.0f} M; not a census, audience or witness estimate \\\\",
          f"Plume & {tex(c['plume']['regime'])}; {pl_txt} \\\\",
          f"Crater & rim diameter {rim['all'][0]:.0f}--{rim['all'][2]:.0f} m (vertical-component rule {rim['vertical-component'][0]:.0f}--{rim['vertical-component'][2]:.0f} m; vertical-equivalent {rim['vertical-equivalent'][0]:.0f}--{rim['vertical-equivalent'][2]:.0f} m), {c['crater']['angular_size_arcsec']:.4f}$''$ from Earth \\\\",
          f"Orbital follow-up & {lro_txt}; P(LRO operating in 2028) = {c['orbiters']['lro']['p_operational_assumed']} (sensitivity {c['orbiters']['lro']['p_operational_sensitivity'][0]}--{c['orbiters']['lro']['p_operational_sensitivity'][1]}), a scenario input, not a probability of imaging the crater; {tex(c['orbiters']['lro']['latency_summary'])} (heuristic); {dan_txt} \\\\",
          r'\bottomrule', r'\end{tabularx}', '']
open(f'{SEC}/B_scenarios.tex', 'w').write('\n'.join(B))

# =====================================================================================================================
# NUMBERS (macros)
# =====================================================================================================================
# ---------------- ephemeris, frames, times
iers = json.load(open(need('outputs/validation/iers_provenance.json')))
nm('iersVersion', iers['version'].replace('.', '.\\allowbreak ')); nm('iersMeasured', iers['measured_until']); nm('iersPredicted', iers['predicted_until'])
nm('iersHeld', iers['ut1_utc_held_s'], '{:+.3f}'); nm('iersBound', iers['ut1_utc_bound_beyond_table_s'], '{:.3f}'); nm('iersRot', iers['rotation_bound_arcsec'], '{:.1f}')
lts = [x for c in cards.values() for x in (c['latency']['light_time_station_range_s'] or [])]
nm('ltMin', min(lts), '{:.2f}'); nm('ltMax', max(lts), '{:.2f}')
ev = json.load(open(need('outputs/validation/ephemeris_validation.json')))
def degsci(x):
    return sci(x, 1)
nm('valRange', ev['range_km']['max'], '{:.3f}')
nm('valSE', '$' + degsci(max(ev['se_astr']['lon_max'], ev['se_astr']['lat_max'])) + '$')
nm('valSS', '$' + degsci(max(ev['ss_like']['lon_max'], ev['ss_like']['lat_max'])) + '$')
nm('valGeomMax', max(ev['se_geom']['lon_max'], ev['se_geom']['lat_max'], ev['ss_geom']['lon_max'], ev['ss_geom']['lat_max']), '{:.3f}')
nm('valTopo', max(v for k, v in ev.items() if k.startswith('topo_')), '{:.3f}')
nm('valIAU', max(ev['de421_vs_iau_2029']['lon_rms'], ev['de421_vs_iau_2029']['lat_rms']), '{:.4f}')
nm('valFail', len(ev['failures']), '{:d}')
# ---------------- screening domain and convergence
cl = np.load(need('outputs/screening/classes.npz')); mp = np.load(need('outputs/screening/maps.npz'))
nm('nHours', thou(len(cl['jd_utc']))); nm('domDays', len(cl['jd_utc']) / 24, '{:.0f}')
cv = pd.read_csv(need('outputs/tables/convergence.csv'))
nm('convGridVis', cv.d_vis_grid.abs().max(), '{:.3f}'); nm('convGridFlash', cv.d_flash_grid.abs().max(), '{:.3f}')
nm('convTime', max(cv.d_vis_time.abs().max(), cv.d_flash_time.abs().max()), '{:.4f}')
lat_p, lon_p = mp['lat'], mp['lon']
lib = (np.abs(lon_p) >= 80) & (np.abs(lon_p) <= 90) & (np.abs(lat_p) < 60)
nm('libMin', 100 * mp['frac_visible'][lib].min(), '{:.0f}'); nm('libMax', 100 * mp['frac_visible'][lib].max(), '{:.0f}'); nm('libMean', 100 * mp['frac_visible'][lib].mean(), '{:.0f}')
nm('flashMax', 100 * mp['frac_flash'].max(), '{:.0f}')
def nearest_pix(la, lo):
    v = np.array([np.cos(np.radians(lat_p)) * np.cos(np.radians(lon_p)), np.cos(np.radians(lat_p)) * np.sin(np.radians(lon_p)), np.sin(np.radians(lat_p))])
    u = np.array([np.cos(np.radians(la)) * np.cos(np.radians(lo)), np.cos(np.radians(la)) * np.sin(np.radians(lo)), np.sin(np.radians(la))])
    return int(np.argmax(u @ v))
k1 = nearest_pix(cards['S1']['lat'], cards['S1']['lon'])
nm('cwCovThree', mp['h_cov3'][k1], '{:.0f}'); nm('cwTr', mp['h_tr'][k1], '{:.0f}')
low = np.abs(lat_p) < 30; pol = np.abs(lat_p) > 84
nm('plumeLowLo', 100 * np.percentile(mp['frac_plume'][low & (np.abs(lon_p) < 75)], 10), '{:.1f}'); nm('plumeLowHi', 100 * np.percentile(mp['frac_plume'][low & (np.abs(lon_p) < 75)], 90), '{:.1f}')
nm('plumePolarMax', 100 * mp['frac_plume'][pol].max(), '{:.0f}')
da = pd.read_csv(need('outputs/tables/daily_availability.csv')); da['month'] = pd.to_datetime(da.day).dt.month
nm('trWinterMax', da[da.month.isin([11, 12, 1, 2])].hours_tr_phase.max(), '{:.0f}')
nm('trSummerMax', da[da.month.isin([6, 7, 8])].hours_tr_phase.max(), '{:.0f}')
nm('trSummerDays', int((da[da.month.isin([6, 7, 8])].hours_tr_phase > 0).sum()), '{:d}'); nm('trWinterDays', int((da[da.month.isin([11, 12, 1, 2])].hours_tr_phase > 0).sum()), '{:d}')
# ---------------- reachability
dv = cards['S1']['reachability']['plane_change_dv_m_s']; nm('dvSix', dv['0.6'], '{:.0f}'); nm('dvTwoFive', dv['2.5'], '{:.0f}')
deo = [R.deorbit_trajectory(fam['altitude_km'], d) for d in fam['deorbit_dv_m_s']]
nm('deoMin', min(x[2] for x in deo) / 60, '{:.0f}'); nm('deoMax', max(x[2] for x in deo) / 60, '{:.0f}')
nm('deoAngLo', min(x[1] for x in deo), '{:.1f}'); nm('deoAngHi', max(x[1] for x in deo), '{:.1f}'); nm('deoV', np.mean([x[0] for x in deo]), '{:.2f}')
nm('jTwo', R.j2_nodal_rate_deg_day(fam['family_sets']['incl88_j2']['inclination_deg'], fam['altitude_km']), '{:.3f}')
twp = pd.read_csv(need('outputs/tables/timeline_window_probability.csv'))
mm_ = twp[twp.family_set == 'main'].set_index(['launch', 'science_months', 'cls', 'delta']); jj_ = twp[twp.family_set == 'incl88_j2'].set_index(['launch', 'science_months', 'cls', 'delta'])
dj = [abs(mm_.loc[i][c_] - jj_.loc[i][c_]) for i in mm_.index if i in jj_.index for c_ in ('p_14d', 'p_30d', 'p_60d') if pd.notna(mm_.loc[i][c_]) and pd.notna(jj_.loc[i][c_])]
nm('jTwoMax', max(dj), '{:.2f}')
# the class-A 60-day minimum (worst start day): the evenings on which its opportunities fall (marginal summer crescents)
zo = np.load(need('outputs/reachability/opportunities_main.npz')); d0_ = fam['cross_track_tolerance_deg'][0]
occA = np.unpackbits(zo['occ'][:, :, list(zo['classes']).index('A_turkiye_evening_public'), list(zo['deltas']).index(d0_), :], axis=-1,
                     count=int(zo['n_hours'])).astype(bool).reshape(-1, int(zo['n_hours']))
stA, pA = OP.window_prob(occA, 60); h_min = int(stA[np.argmin(pA)])
hrs = np.where(occA[:, h_min:h_min + 60 * 24].any(axis=0))[0] + h_min
import datetime as dt_
jd_ist = cl['jd_utc'][hrs] + 3 / 24.0                                                                     # Istanbul time (UTC+3)
evenings = sorted({(dt_.datetime(2000, 1, 1, 12) + dt_.timedelta(days=float(j) - 2451545.0)).date() for j in jd_ist})
nm('wASixtyMinBasis', (f'a single evening, {evenings[0].day}~{evenings[0].strftime("%B")}~{evenings[0].year}' if len(evenings) == 1 else f'{len(evenings)} evenings'))
oc = pd.read_csv(need('outputs/tables/opportunity_convergence.csv'))
nm('ocMax', oc[oc.subset.isin(['nodes/2', 'phases/2', 'both/2'])].d_mean_p30.abs().max(), '{:.3f}')
dr1 = oc[oc.subset == 'direction 1'].set_index(['cls', 'delta']); dr2 = oc[oc.subset == 'direction 2'].set_index(['cls', 'delta'])   # GE-V2-02
nm('dirMean', (dr1.mean_p30 - dr2.mean_p30).abs().max(), '{:.3f}')
nm('dirMin', (dr1.min_p30 - dr2.min_p30).abs().max(), '{:.3f}'); nm('dirFirst', (dr1.p_first_3mo - dr2.p_first_3mo).abs().max(), '{:.3f}')
rcv = pd.read_csv(need('outputs/tables/reachability_convergence.csv')); rcv = rcv[~rcv.variant.str.startswith('production')]
small3 = lambda v: '$<$0.001' if v < 0.0005 else f'{v:.3f}'
for kind, kn in (('numerical', 'Num'), ('sampling', 'Sam'), ('burn', 'Burn')):            # numerical refinement, other planes/phases, 50-m/s burn
    rk = rcv[rcv.kind == kind]
    z3 = lambda v: '0' if v < 1e-12 else small3(v)
    nm(f'rc{kn}P', z3(rk.d_mean_p30.abs().max())); nm(f'rc{kn}Min', z3(rk.d_min_p30.abs().max()))
    nm(f'rc{kn}F', z3(rk.d_p_first_3mo.abs().max())); nm(f'rc{kn}H', 100 * rk.rel_d_opp_hours.abs().max(), '{:.1f}')
d0, d1 = fam['cross_track_tolerance_deg']
nm('rchCenCov', rreg(d0, 'flash_cov3', 'near side central'), '{:.1f}'); nm('rchCenTr', rreg(d0, 'flash_tr', 'near side central'), '{:.1f}')
nm('rchPolCov', rreg(d0, 'flash_cov3', 'polar'), '{:.1f}'); nm('rchPolTr', rreg(d0, 'flash_tr', 'polar'), '{:.1f}')
nm('rchLimbCov', np.mean([rreg(d0, 'flash_cov3', r_) for r_ in ('eastern limb region', 'western limb region')]), '{:.1f}')
nm('rchGain', rreg(d1, 'flash_cov3', 'near side central') / rreg(d0, 'flash_cov3', 'near side central'), '{:.1f}')
nm('rchCenFrac', 100 * rreg(d0, 'flash_tr', 'near side central', 'frac_pixels_nonzero'), '{:.0f}')
for cls, C_ in CLS.items():
    for dl, suf in ((d0, ''), (d1, 'PC')):
        for Wd, wn in ((30, 'Thirty'), (60, 'Sixty'), (90, 'Ninety')):
            nm(f'w{C_}{wn}Mean{suf}', wstat(cls, dl, Wd, 'mean')); nm(f'w{C_}{wn}Min{suf}', wstat(cls, dl, Wd, 'min'))
        nm(f'w{C_}ThirtyHalf{suf}', 100 * wstat(cls, dl, 30, 'half'), '{:.0f}')
        for N, nn in ((3, 'Three'), (6, 'Six'), (12, 'Twelve')):
            nm(f'fs{C_}{nn}{suf}', fstart(cls, dl, N))
        nl, nlt = lun(cls, dl)
        nm(f'lun{C_}Lo{suf}', int(nl.min()), '{:d}'); nm(f'lun{C_}Hi{suf}', int(nl.max()), '{:d}'); nm(f'lun{C_}Mean{suf}', nl.mean(), '{:.1f}')
        fa_ = ost[(ost.cls == cls) & (np.isclose(ost.delta, dl))].first_after_ref_days
        nm(f'first{C_}Max{suf}', fa_.max(), '{:.0f}')
nm('nLun', lun('A_turkiye_evening_public', d0)[1], '{:d}')
nm('plumeGain', lun('P_plume_global', d1)[0].mean() / max(lun('P_plume_global', d0)[0].mean(), 1e-9), '{:.1f}')
nm('oppAPct', 100 * lun('A_turkiye_evening_public', d0)[0].mean() / lun('A_turkiye_evening_public', d0)[1], '{:.0f}')
# ---------------- terrain
hz = np.load(need('outputs/scenarios/synthetic_horizons.npz'))
nm('hzLow', float(np.median(hz['low'])), '{:.2f}'); nm('hzMed', float(np.median(hz['medium'])), '{:.2f}'); nm('hzHigh', float(np.median(hz['high'])), '{:.2f}')
# ---------------- flash model and priors
c1 = cards['S1']; m1 = c1['mc'][PRIOR]
lab = c1['lab_trend']; nm('labEta', '$' + sci(lab['eta_vis']) + '$'); nm('labV', lab['V_peak'], '{:.0f}')
nm('labEtaTwoFour', '$' + sci(float(I.lab_trend_eta(2.4))) + '$')
nm('rejWide', 100 * m1['rejected_fraction'], '{:.1f}'); nm('rejV', 100 * c1['mc'][PRIOR_V]['rejected_fraction'], '{:.1f}')
nm('rejCool', 100 * c1['mc']['wide|cool']['rejected_fraction'], '{:.0f}')
for T0, tag in [(3500, 'Hot'), (2500, 'Mid'), (1800, 'Cool')]:
    f_ = FM(1e-4, T0); nm(f'kv{tag}', f_.peak_magnitude('V', d38) - f_.peak_magnitude('Ks', d38), '{:.1f}')
fm = FM(1e-4)
for b in ['V', 'Rc', 'Ic', 'J', 'H', 'Ks']:
    nm(f'pk{b}', fm.peak_magnitude(b, d38), '{:.1f}')
nm('ksSix', FM(1e-6).peak_magnitude('Ks', d38), '{:.1f}')
nm('dilTen', fm.exposure_averaged_magnitude('Ks', 10.0, distance_m=d38) - fm.peak_magnitude('Ks', d38), '{:.1f}')
fs_ = FM(1e-4, Ek=I.kinetic_energy(285, 2.0))
nm('smartAvg', fs_.exposure_averaged_magnitude('Ks', 10.0, distance_m=d38), '{:.1f}'); nm('smartPk', fs_.peak_magnitude('Ks', d38), '{:.1f}')
for T0, tag in [(1800, 'Cool'), (2500, 'Mid'), (3500, 'Hot')]:
    lo, hi = I.smart1_saturation_eta(T0, 0.5, overexposure=(1.0, 1.0)); nm(f'smSatLo{tag}', '$' + sci(lo) + '$'); nm(f'smSatHi{tag}', '$' + sci(hi) + '$')
    lo10, _ = I.smart1_saturation_eta(T0, 0.5, overexposure=(10.0, 10.0)); nm(f'smOverLo{tag}', '$' + sci(lo10) + '$')
pk = json.load(open(need('outputs/tables/peak_magnitude_distribution.json')))
pw, pv = pk['peakV_wide'], pk['peakV_v-scaled']
nm('pkWideMed', pw['p50'], '{:.1f}'); nm('pkWideLo', pw['p5'], '{:.1f}'); nm('pkWideHi', pw['p95'], '{:.1f}')
nm('pkVMed', pv['p50'], '{:.1f}'); nm('pkVLo', pv['p5'], '{:.1f}'); nm('pkVHi', pv['p95'], '{:.1f}')
def pct(x):
    return '0' if x == 0 else '$<$0.01' if 100 * x < 0.01 else f'{100 * x:.2f}' if 100 * x < 1 else f'{100 * x:.0f}'
nm('fracNakedWide', pct(pw['p_brighter_than_none_median_threshold'])); nm('fracBinWide', pct(pw['p_brighter_than_binoculars_median_threshold']))
nm('fracEyeWide', pct(pw['p_brighter_than_telescope20cm_median_threshold'])); nm('fracEyeV', pct(pv['p_brighter_than_telescope20cm_median_threshold']))
nm('fracBinV', pct(pv['p_brighter_than_binoculars_median_threshold']))
vt = pk['visual_thresholds_V']
for a_, tag in (('none', 'Naked'), ('binoculars', 'Bin'), ('telescope20cm', 'Eye')):
    nm(f'vt{tag}Lo', vt[a_]['F24'], '{:.1f}'); nm(f'vt{tag}Hi', vt[a_]['F1p4'], '{:.1f}')
# ---------------- instrument limits (same instrument construction as the Monte Carlo; illum 0.35, 8' from sunlit terrain, Sun -20, airmass 1.2)
LIMN = {'lunar_impact_system': 'Nel', 'fast_camera_large': 'Fast', 'tug_t100_qhy': 'Thund', 'amateur_class': 'Am', 'nir_large': 'Nir', 'dag_dirac': 'Dirac', 'rtt150_fast': 'Rtt', 'dag_visitor_fast': 'Dagv', 'fast_camera_possible': 'Fposs', 'midas_video': 'Midas'}
for tname, tag in LIMN.items():
    st = MC.Station(dict(id='X', lat=0, lon=0, alt=2500.0, group='x'), tname, templates[tname], 0.5)
    band = templates[tname]['bands'][0]; inst = st.instrument(band)
    ext = float(D.extinction_mag(band, 1.2, 2500.0)); bk = D.total_background_sb(band, 0.35, 8.0, -20, ext_mag=ext)
    nm(f'lim{tag}', D.limiting_magnitude(inst, bk, 8.0) - ext, '{:.1f}'); nm(f'sat{tag}', D.bright_limit(inst, bk) - ext, '{:.1f}')
# ---------------- injection-recovery
nm('injNtrial', int(inj['nel']['ntrial']), '{:d}'); nm('injNseq', thou(inj['nel']['n_seq'])); nm('injSeed', int(inj['_settings']['seed']), '{:d}')
nm('injBox', int(inj['_settings']['box_px']), '{:d}'); nm('injNclips', int(inj['nel']['false_alarms']['n_clips']), '{:d}')
nm('injMaxShift', max(inj[k]['registration']['max_abs_shift_px'] for k in inj if not k.startswith('_')), '{:.1f}')
nm('injAtLimit', sum(inj[k]['registration']['frames_at_search_limit'] for k in inj if not k.startswith('_')), '{:d}')
for key, tag in INJ_TAG.items():
    r = inj[key]; f0 = r['fits']['cam0']; fa = r['false_alarms']; c0 = fa['candidate_rate_per_box_frame'][0]
    nm(f'inj{tag}Mfifty', f0['m50'], '{:.1f}'); nm(f'inj{tag}MfiftyLo', f0['m50_ci95'][0], '{:.1f}'); nm(f'inj{tag}MfiftyHi', f0['m50_ci95'][1], '{:.1f}')
    nm(f'inj{tag}Mninety', f0['m90'], '{:.1f}'); nm(f'inj{tag}An', r['analytic_limits']['steady_snr8'], '{:.1f}'); nm(f'inj{tag}AnFive', r['analytic_limits']['steady_snr5'], '{:.1f}')
    nm(f'inj{tag}Fa', c0['rate'], '{:.4f}'); nm(f'inj{tag}FaHi', c0['ci95_clip_bootstrap'][1], '{:.4f}'); nm(f'inj{tag}FaN', int(c0['total']), '{:d}')
    nm(f'inj{tag}FaWin', fa['expected_false_candidates_per_injection_window'], '{:.2f}')
    nm(f'inj{tag}Gap', r['analytic_limits']['steady_snr8'] - f0['m50'], '{:+.1f}')
    f40 = r['fits'].get('cam0_first40_frames')
    if f40:
        nm(f'inj{tag}MfiftyFirstForty', f40['m50'], '{:.2f}'); nm(f'inj{tag}DFirstForty', f40['m50'] - f0['m50'], '{:+.2f}')
fd = inj['nel']['fits']['dual']; nm('injNelDualMfifty', fd['m50'], '{:.1f}'); nm('injNelDualMninety', fd['m90'], '{:.1f}')
dc = inj['nel']['false_alarms'].get('dual_coincidence_rate_per_box_frame')
nm('injNelCoincN', int(dc['total']) if dc else 0, '{:d}'); nm('injNelCoincHi', dc['ci95_clip_bootstrap'][1] if dc else float('nan'), '{:.4f}')
nm('injNelFaFrames', thou(inj['nel']['false_alarms']['candidate_rate_per_box_frame'][0]['box_frames']))
nm('injMedFrames', int(round(inj['nel']['false_alarms']['median_frames_per_injection'])), '{:d}')
nm('nelSNR', inj['_neliota_check']['model_snr_at_12_41'], '{:.1f}')
nm('injMaxDFirstForty', max(abs(inj[k]['fits']['cam0_first40_frames']['m50'] - inj[k]['fits']['cam0']['m50']) for k in INJ_TAG if 'cam0_first40_frames' in inj[k]['fits']), '{:.2f}')
# ---------------- ejecta checks (LCROSS, crater consistency)
ej = json.load(open(need('outputs/tables/ejecta_checks.json')))
lcm = {(x['model'], x['params']): x['M_illuminated_kg'] for x in ej['lcross']}
nm('lcFly', lcm[('Centaur as 400 kg/m3', 'sand/fly ash')], '{:.0f}'); nm('lcSand', lcm[('Centaur as 400 kg/m3', 'sand')], '{:.0f}'); nm('lcPerl', lcm[('Centaur as 400 kg/m3', 'perlite/sand')], '{:.0f}')
dense = [v for (m_, p_), v in lcm.items() if m_ == 'dense parts + hollow']; nm('lcDenseLo', min(dense), '{:.0f}'); nm('lcDenseHi', max(dense), '{:.0f}')
nm('lcHollowMax', max(v for (m_, p_), v in lcm.items() if m_ == 'hollow Centaur'), '{:.0f}')
CC = {'GRAIL': 'Grail', 'LADEE': 'Ladee', 'Falcon': 'Falcon', 'LCROSS': 'Lcross'}
for x in ej['crater_consistency']:
    tag = next(v for k_, v in CC.items() if x['case'].startswith(k_))
    for rule, rt in (('vertical-component', 'Vc'), ('vertical-equivalent', 'Ve')):
        nm(f'cc{tag}{rt}Lo', x[rule][0], '{:.1f}' if x[rule][0] < 10 else '{:.0f}'); nm(f'cc{tag}{rt}Hi', x[rule][1], '{:.1f}' if x[rule][1] < 10 else '{:.0f}')
    nm(f'cc{tag}Obs', x['observed_m'], '{:.0f}')
env = ej['ballistic_envelope_m']
nm('crBalLo', env['all'][0], '{:.0f}'); nm('crBalMed', env['all'][1], '{:.0f}'); nm('crBalHi', env['all'][2], '{:.0f}')
nm('crVcLo', env['vertical-component'][0], '{:.0f}'); nm('crVcHi', env['vertical-component'][2], '{:.0f}'); nm('crVeLo', env['vertical-equivalent'][0], '{:.0f}'); nm('crVeHi', env['vertical-equivalent'][2], '{:.0f}')
br = [I.crater_rim_diameter_envelope(np.mean(cfg['physics'][k]['mass_kg']), cfg['physics'][k]['v_km_s'], cfg['physics'][k]['angle_deg'])['all'] for k in ['V_MOD', 'V_STR', 'V_NSL']]
nm('crBrLo', min(x[0] for x in br), '{:.0f}'); nm('crBrHi', max(x[2] for x in br), '{:.0f}')
nm('crAng', c1['crater']['angular_size_arcsec'], '{:.3f}'); nm('crNac', c1['crater']['lroc_nac_pixels_median'], '{:.0f}')
# ---------------- plume numbers
def plume_best(sid):
    det = [x for x in cards[sid]['plume']['cases'] if x.get('observers', {}).get('TUG')]
    if not det:
        return None
    return dict(snr=max(x['observers']['TUG']['sys0.001']['snr_max'] for x in det), snr2=max(x['observers']['TUG']['sys0.01']['snr_max'] for x in det),
                con=max(x['observers']['TUG']['sys0.001']['contrast_max'] for x in det),
                m=max(x['observers']['TUG']['M_vis_max_kg'] for x in det), n=len(det), N=len(cards[sid]['plume']['cases']),
                vneed=min(x['v_needed_m_s'] for x in cards[sid]['plume']['cases']), vmax=max(x['vmax_domain_m_s'] for x in det))
for sid in ['S2', 'S5', 'S8']:
    b_ = plume_best(sid); w = W[sid]
    nm(f'plSnr{w}', b_['snr'], '{:.1f}'); nm(f'plSnrSys{w}', b_['snr2'], '{:.2f}'); nm(f'plM{w}', KG(b_['m'])); nm(f'plN{w}', b_['n'], '{:d}'); nm(f'plNall{w}', b_['N'], '{:d}')
    nm(f'plVneed{w}', b_['vneed'], '{:.0f}'); nm(f'plVmax{w}', b_['vmax'], '{:.0f}'); nm(f'plCon{w}', 100 * b_['con'], '{:.1f}')
for sid in ['S1', 'S2', 'S8']:
    nm(f'sh{W[sid]}', cards[sid]['geometry']['shadow_height_km'], '{:.0f}' if cards[sid]['geometry']['shadow_height_km'] > 20 else '{:.1f}')
allsnr = [x['observers']['TUG']['sys0.001']['snr_max'] for c in cards.values() for x in c['plume']['cases'] if 'TUG' in x.get('observers', {})]   # the 1-m telescope at TUG, as in Table 9
nm('plSnrAll', max(allsnr), '{:.1f}')
def plume_sens(sid, key):
    det = [x['observers']['TUG'] for x in cards[sid]['plume']['cases'] if x.get('observers', {}).get('TUG')]
    return det, [d[key] for d in det if key in d]
for sid in ['S2', 'S5', 'S8']:
    det, _ = plume_sens(sid, 'grains_sys0.001'); w = W[sid]
    mx = lambda v, f: f.format(max(v)) if v else '--'
    fine = [d['grains_sys0.001']['fine-rich'] for d in det]; coarse = [d['grains_sys0.001']['coarse'] for d in det]
    corner = [d['optimistic_corner_sys0.001']['snr_max'] for d in det]; pphi = [d['pphi_sys0.001']['0.1'] for d in det]
    nm(f'plFine{w}', mx(fine, '{:.1f}')); nm(f'plCoarse{w}', mx(coarse, '{:.1f}')); nm(f'plCorner{w}', mx(corner, '{:.0f}')); nm(f'plPphiHi{w}', mx(pphi, '{:.1f}'))
    nm(f'plKappaOne{w}', mx([d['kappa_sys0.001']['1'] for d in det if 'kappa_sys0.001' in d], '{:.1f}'))
    nm(f'plMcon{w}', KG(max(d['M_contrast_class_max_kg'] for d in det)) if det else '--')
pc = pd.read_csv(need('outputs/tables/plume_convergence.csv'))
NUMV = ['fine cell 25 m', 'fine cell 100 m', 'coarse cell 0.25 km', 'coarse cell 1 km', 'particles x8 (96 x 14 x 32)', 'time step x0.5', 'record step x0.5']
for sid in ['S2', 'S5']:
    x = pc[pc.scenario == sid].set_index('variant'); b0 = x.loc['production', 'snr_regolith_sys1e3']; w = W[sid]
    nm(f'pcNum{w}', 100 * max(abs(x.loc[v, 'snr_regolith_sys1e3'] / b0 - 1) for v in NUMV), '{:.0f}')
    nm(f'pcFloor{w}', 100 * max(abs(x.loc[v, 'snr_regolith_sys1e3'] / b0 - 1) for v in ('speed floor 0.5 m/s', 'speed floor 2 m/s', 'speed floor 5 m/s')), '{:.0f}')
    nm(f'pcPoint{w}', 100 * abs(x.loc['point source at t = 0', 'snr_regolith_sys1e3'] / b0 - 1), '{:.0f}')
    dw_ = 100 * (x.loc['window 0.1 s', 'snr_regolith_sys1e3'] / b0 - 1)
    nm(f'pcWin{w}', dw_, '{:+.0f}'); nm(f'pcWinTxt{w}', f"{'lowers' if dw_ < 0 else 'raises'} the {sid} value by {abs(dw_):.0f}\\%")
# ---------------- Monte Carlo settings and precision
ms = c1['mc_settings']; nm('nOuter', ms['n_outer'], '{:d}'); nm('nInner', ms['n_inner'], '{:d}'); nm('nEvents', thou(ms['n_outer'] * ms['n_inner']))
hw = [1.96 * m['mc_se'] for c in cards.values() for pri in (PRIOR, PRIOR_V) for s in c['mc'][pri]['strategies'].values() for o, m in s.items() if isinstance(m, dict) and 'mc_se' in m and m['mc_se'] is not None and np.isfinite(m['mc_se'])]
nm('mcHalfMax', np.ceil(max(hw) * 100) / 100, '{:.2f}')
ic = c1['mc_inner_convergence']; ni_ = sorted(ic, key=int)
nm('icSmall', int(ni_[0]), '{:d}'); nm('icLarge', int(ni_[-1]), '{:d}')
def width(m):
    return m['outer_p95'] - m['outer_p05']
def raw_width(m):
    return m['outer_raw_p95'] - m['outer_raw_p05']
dw = [abs(width(ic[n][st][o]) - width(ic[ni_[-1]][st][o])) for n in ni_ for st in SL for o in ('any', 'two_indep')]
nm('icMaxDW', max(dw), '{:.2f}')
nm('icRawSmall', raw_width(ic[ni_[0]]['B_global_science']['any']), '{:.2f}'); nm('icRawLarge', raw_width(ic[ni_[-1]]['B_global_science']['any']), '{:.2f}')
nm('icDecSmall', width(ic[ni_[0]]['B_global_science']['any']), '{:.2f}'); nm('icDecLarge', width(ic[ni_[-1]]['B_global_science']['any']), '{:.2f}')
for sid in ('S1', 'S11'):
    ws = cards[sid]['mc_weather_sensitivity']; w = W[sid]
    base = {(st, o): mcs(sid, st, o)['p'] for st in SL for o in ('any', 'two_indep', 'confirmed')}
    dd = {v: max(abs(ws[v][st][o]['p'] - base[(st, o)]) for st in SL for o in ('any', 'two_indep', 'confirmed')) for v in ws}
    nm(f'wsMax{w}', max(dd.values()), '{:.2f}'); nm(f'wsMaxVar{w}', max(dd, key=dd.get))
    for v, tag in (('flat season', 'Flat'), ('L = 250 km', 'Lshort'), ('L = 1000 km', 'Llong'), ('prior spread x0.5', 'Narrow'), ('prior spread x2', 'Wide')):
        nm(f'ws{tag}{w}', fp(ws[v]['B_global_science']['any']['p'])); nm(f'wsTwo{tag}{w}', fp(ws[v]['B_global_science']['two_indep']['p']))
# ---------------- per-scenario probabilities
for sid in order:
    c = cards[sid]; w = W[sid]
    for strat, S in SL.items():
        for out, k in OUT.items():
            m = mcs(sid, strat, out)
            nm(f'{k}{S}{w}', fp(m['p'])); nm(f'{k}{S}{w}Lo', fp(m['outer_p05'])); nm(f'{k}{S}{w}Hi', fp(m['outer_p95']))
            nm(f'{k}{S}{w}V', fp(mcs(sid, strat, out, PRIOR_V)['p']))
        for pri, suf in (('wide|cool', 'Cool'), ('wide|narrow', 'Narrow')):
            if pri in c['mc']:
                for out, k in (('any', 'any'), ('two_indep', 'two'), ('confirmed', 'conf')):
                    nm(f'{k}{S}{w}{suf}', fp(mcs(sid, strat, out, pri)['p']))
    vis = c['public']['visual']
    for a_, tag in (('none', 'naked'), ('binoculars', 'bin'), ('telescope20cm', 'eye')):
        nm(f'{tag}{w}', fsmall(vis[a_]['p_conditional']) if vis.get('observable') else '0'); nm(f'{tag}{w}W', fsmall(vis[a_]['p_with_weather']) if vis.get('observable') else '0')
    nm(f'nsites{w}', int(c['n_sites_available']), '{:d}'); nm(f'ntr{w}', len(c['turkish_sites_available']), '{:d}')
    pr = c['population']['by_radius']
    nm(f'pop{w}', pr['10km']['public'] / 1e9); nm(f'pop{w}Lo', pr['25km']['public'] / 1e9); nm(f'pop{w}Hi', pr['0km']['public'] / 1e9); nm(f'popTr{w}', pr['10km']['turkiye_public'] / 1e6, '{:.0f}')
    pkv = c['mc'][PRIOR]['peakV']; nm(f'pkmed{w}', pkv['median'], '{:.1f}'); nm(f'pklo{w}', pkv['p10'], '{:.1f}'); nm(f'pkhi{w}', pkv['p90'], '{:.1f}')
    nm(f'Ek{w}', c['energy']['E_k_J'] / 1e9); nm(f'illum{w}', c['moon']['illum_frac'])
    nm(f'em{w}', c['geometry']['emission_geocentric'], '{:.0f}'); nm(f'inc{w}', c['geometry']['incidence'], '{:.0f}')
    rc = c['reachability']
    if rc.get('status') == 'conditional':
        nm(f'pPlane{w}', rc['p_random_polar_plane_within']['0.6'], '{:.3f}'); nm(f'pPlane{w}PC', rc['p_random_polar_plane_within']['2.5'], '{:.3f}')
    tr_ = c['terrain']['p_terrain_range']; nm(f'terr{w}', f'{tr_[0]:.2f}--{tr_[1]:.2f}')
nm('popTrLo', min(c['population']['by_radius']['10km']['turkiye_public'] for c in cards.values() if c['population']['by_radius']['10km']['turkiye_public'] > 0) / 1e6, '{:.0f}')
for out, k in OUT.items():       # ranges over the three strategies for S1 (order-independent)
    v = [mcs('S1', st, out)['p'] for st in SL]; nm(f'{k}RangeOne', f'{fp(min(v))}--{fp(max(v))}')
nm('altTUGOne', c1['sites']['TUG']['moon_alt'], '{:.0f}'); nm('altDAGOne', c1['sites']['DAG']['moon_alt'], '{:.0f}')
nm('reclassOne', c1['population']['n_reclassified_vs_grid'], '{:d}'); nm('reclassPopOne', c1['population']['pop_reclassified_vs_grid'] / 1e6, '{:.0f}')
# S1 details: stations, DIRAC, eta bins, naive formula, paired differences
sB = m1['strategies']['B_global_science']; sC = m1['strategies']['C_public_participation']
nm('diracCovOne', sB['station_p_fov']['DAG:dag_dirac']); nm('diracPOne', sB['station_p_det']['DAG:dag_dirac'])
FR = {'SAAO:fast_camera_large': 'the Sutherland fast camera', 'KRY:lunar_impact_system': 'NELIOTA', 'KOT:fast_camera_possible': 'a visitor camera at Kottamia', 'TUG:rtt150_fast': 'a fast camera on RTT150',
      'MAID:fast_camera_possible': 'a visitor camera at Maidanak', 'TUG:tug_t100_qhy': 'TUG T100 with its GPS camera', 'SAO:fast_camera_large': 'the Zelenchukskaya station', 'DAG:dag_visitor_fast': 'a visitor camera on DAG',
      'BYU:fast_camera_possible': 'a visitor camera at Byurakan', 'SEV:midas_video': 'MIDAS', 'ORM:fast_camera_large': 'a La Palma fast camera', 'DAG:dag_dirac': 'DAG DIRAC',
      'WISE:fast_camera_possible': 'a visitor camera at Wise', 'HAN:fast_camera_possible': 'a visitor camera at Hanle', 'SAAO:nir_large': 'a near-infrared camera at Sutherland', 'SAO:nir_large': 'a near-infrared camera at Zelenchukskaya'}
top = [(k, v) for k, v in sorted(sB['station_p_det'].items(), key=lambda x: -x[1]) if v > 0][:6]
nm('stationsOne', ', '.join(f"{FR.get(k, k.replace('_', ' '))} ({v:.2f})" for k, v in top[:-1]) + f", and {FR.get(top[-1][0], top[-1][0].replace('_', ' '))} ({top[-1][1]:.2f})")
nm('nStatB', sB['n_stations'], '{:d}'); nm('nStatC', sC['n_stations'], '{:d}'); nm('nStatA', m1['strategies']['A_turkiye_priority']['n_stations'], '{:d}')
bins = m1['eta_bins']
for strat, S in (('B_global_science', 'B'), ('A_turkiye_priority', 'A')):
    for out, k in (('any', 'Any'), ('confirmed', 'Conf'), ('two_indep', 'Two')):
        be = m1['strategies'][strat][out]['by_eta']
        nm(f'eta{k}Lo{S}', fp(be[0])); nm(f'eta{k}Hi{S}', fp(be[-1]))
        up = [x for lo_, x in zip(bins[:-1], be) if lo_ >= -4.0 and x is not None]
        nm(f'eta{k}Up{S}', f'{min(up):.2f}' if f'{min(up):.2f}' == f'{max(up):.2f}' else f'{min(up):.2f}--{max(up):.2f}')
for strat, lab_ in (('B_global_science', 'B'), ('C_public_participation', 'C')):
    p_ = np.array(list(m1['strategies'][strat]['station_p_det'].values())); naive = 1 - np.prod(1 - p_)
    nm(f'naive{lab_}', naive); nm(f'over{lab_}', naive - m1['strategies'][strat]['any']['p'])
pdiff = m1['paired']
for key, tag in (('any:B_global_science-A_turkiye_priority', 'dBAany'), ('two_indep:B_global_science-A_turkiye_priority', 'dBAtwo'),
                 ('confirmed:C_public_participation-B_global_science', 'dCBconf'), ('live:C_public_participation-B_global_science', 'dCBlive'),
                 ('any:C_public_participation-B_global_science', 'dCBany'), ('two_indep:C_public_participation-B_global_science', 'dCBtwo')):
    d_ = pdiff[key]
    sg = lambda v: ('$+$' if round(v, 2) > 0 else '$-$' if round(v, 2) < 0 else '') + f'{abs(v):.2f}'
    nm(tag, sg(d_['diff'])); nm(tag + 'Lo', sg(d_['ci95'][0])); nm(tag + 'Hi', sg(d_['ci95'][1]))
# scenario-to-scenario changes (wide prior; P(any) and P(two sites); all strategies)
def mcv(sid, strat, key):
    return cards[sid]['mc'][PRIOR]['strategies'][strat][key]['p']
def drop(s_ref, s_alt, keys=('any', 'two_indep')):
    d_ = [mcv(s_ref, st, k) - mcv(s_alt, st, k) for st in SL for k in keys]
    return f'{min(d_):.2f}--{max(d_):.2f}'
nm('dropBr', drop('S1', 'S10')); nm('dropJan', drop('S1', 'S11')); nm('dropPlume', drop('S1', 'S2', ('any',)))
# strategies
cr_ = []
for sid in order:
    b_ = so[(so.scenario == sid) & (so.strategy == 'B_global_science')]; cc_ = so[(so.scenario == sid) & (so.strategy == 'C_public_participation')]
    if len(b_) and len(cc_) and cc_.weight_recruited.values[0] > 0:
        cr_.append(b_.weight_recruited.values[0] / cc_.weight_recruited.values[0])
nm('costRatio', f'{min(cr_):.1f}' if round(min(cr_), 1) == round(max(cr_), 1) else f'{min(cr_):.1f}--{max(cr_):.1f}')
a2 = so[so.strategy == 'A_turkiye_priority'].set_index('scenario').p_two_indep
nm('twoAmax', a2.max()); nm('twoAmaxScen', str(a2.idxmax()))
dconf = [mcv(sid, 'B_global_science', 'confirmed') - mcv(sid, 'B_global_science', 'two_indep') for sid in order if sid != 'S9']
nm('confMinusTwo', f'{min(dconf):.2f}--{max(dconf):.2f}')
gap = [mcv(sid, 'B_global_science', 'two_indep') - mcv(sid, 'C_public_participation', 'two_indep') for sid in order if sid != 'S9']
nm('gapTwoBC', f'{min(gap):+.2f} to {max(gap):+.2f}')
def listing(xs):
    xs = list(xs)
    return 'no scenario' if not xs else xs[0] if len(xs) == 1 else ', '.join(xs[:-1]) + ' and ' + xs[-1]
ndt = nd.copy()
allnd = [sid for sid in order if sid != 'S9' and ndt[(ndt.scenario == sid)].nondominated.all()]
adom = [sid for sid in order if sid != 'S9' and not bool(ndt[(ndt.scenario == sid) & (ndt.strategy == 'A_turkiye_priority')].nondominated.values[0])]
cdom = [sid for sid in order if sid != 'S9' and not bool(ndt[(ndt.scenario == sid) & (ndt.strategy == 'C_public_participation')].nondominated.values[0])]
bdom = [sid for sid in order if sid != 'S9' and not bool(ndt[(ndt.scenario == sid) & (ndt.strategy == 'B_global_science')].nondominated.values[0])]
nm('ndAll', listing(allnd)); nm('ndADom', listing(adom)); nm('ndBDom', listing(bdom)); nm('ndCDom', listing(cdom))
cons = lambda strat: [sid for sid in order if sid != 'S9' and not bool(ndt[(ndt.scenario == sid) & (ndt.strategy == strat)].nondominated_conservative.values[0])]
nm('ndAllCons', listing([sid for sid in order if sid != 'S9' and ndt[(ndt.scenario == sid)].nondominated_conservative.all()]))
nm('ndADomCons', listing(cons('A_turkiye_priority'))); nm('ndBDomCons', listing(cons('B_global_science'))); nm('ndCDomCons', listing(cons('C_public_participation')))
darknp = [sid for sid in order if cards[sid]['geometry']['incidence'] > 90 and cards[sid]['region'] != 'polar' and cards[sid]['n_sites_available'] > 0]
rat = [mcv(sid, st, 'two_indep') / mcv(sid, 'A_turkiye_priority', 'two_indep') for sid in darknp for st in ('B_global_science', 'C_public_participation') if mcv(sid, 'A_turkiye_priority', 'two_indep') > 0.01]
nm('twoRatio', f'{min(rat):.1f}--{max(rat):.1f}')
from ayap1obs import weather as Wt
pcl = [Wt.p_clear_month(sites_cfg['TUG'], mo) for mo in range(1, 13)]; nm('cloudTug', f'{1 - max(pcl):.2f}--{1 - min(pcl):.2f}')
# public thresholds and phone limits (S1, Istanbul)
vis1 = c1['public']['visual']
nm('thrNaked', vis1['none']['threshold_median'], '{:.1f}'); nm('thrBin', vis1['binoculars']['threshold_median'], '{:.1f}'); nm('thrEye', vis1['telescope20cm']['threshold_median'], '{:.1f}')
nm('phoneStand', c1['public']['phone_standalone_limit_broad'], '{:.1f}'); nm('phoneAf', c1['public']['phone_afocal20cm_limit_broad'], '{:.1f}')
nm('gapNaked', pw['p50'] - vis1['none']['threshold_median'], '{:.0f}')
nm('moonAltIst', vis1['moon_alt'], '{:.0f}')
# refinement
rw = pd.read_csv(need('outputs/tables/refined_windows.csv')).set_index('id')
r1 = rw.loc['S1']; t1 = pd.Timestamp(r1.epoch_utc)
hm = lambda m: (t1 + pd.Timedelta(minutes=float(m))).strftime('%H:%M'); hmi = lambda m: (t1 + pd.Timedelta(minutes=float(m) + 180)).strftime('%H:%M')
nm('refTugStartOne', hm(r1.tug_window_start_min)); nm('refTugEndOne', hm(r1.tug_window_end_min))
nm('refTugStartIstOne', hmi(r1.tug_window_start_min)); nm('refTugEndIstOne', hmi(r1.tug_window_end_min))
nm('refNminOne', int(r1.n_min_in_window), '{:d}'); nm('refNmaxOne', int(r1.n_max_pm3h), '{:d}')
sp = [float(x.split('-')[1]) - float(x.split('-')[0]) for x in rw.emission_range_deg] + [float(x.split('-')[1]) - float(x.split('-')[0]) for x in rw.incidence_range_deg]
nm('refSpread', max(sp), '{:.1f}')
r4 = rw.loc['S4']; nm('refTugLenFour', float(r4.tug_window_end_min - r4.tug_window_start_min), '{:.0f}')
# timeline families (nominal): window-opening date, sessions, P30 for class A
LW = {'L0': 'Zero', 'L1': 'One', 'L2': 'Two'}; SW = {3: 'Three', 6: 'Six', 12: 'Twelve', 18: 'Eighteen'}
for _, r in tf.iterrows():
    if r.launch in LW and int(r.science_months) in SW:
        t_ = f'tl{LW[r.launch]}{SW[int(r.science_months)]}'
        nm(t_ + 'Date', str(r.impact_date)); nm(t_ + 'N', int(r.n_evening_sessions_pm15d) if pd.notna(r.n_evening_sessions_pm15d) else 0, '{:d}')
        nm(t_ + 'PA', f30(r.p30_A)); nm(t_ + 'PP', f30(r.p30_P))
cal = pd.read_csv(need('outputs/tables/observing_windows_calendar.csv'))
eve = cal[cal.session.str.startswith('evening')]; mor = cal[cal.session.str.startswith('morning')]
nm('calEve', len(eve), '{:d}'); nm('calMorn', len(mor), '{:d}'); nm('calEveMeanH', eve.duration_min.mean() / 60, '{:.1f}'); nm('calEveTen', int((eve.n_sites_available >= 10).sum()), '{:d}')
# orbiter latency precedents (impacts only)
ol = pd.read_csv(need('research/orbiter_latency.csv')); imp = ol[ol.event_class.str.contains('impact') & ~ol.event_class.str.contains('natural')]
good = imp[imp.days_event_to_first_image <= 15]; poor = imp[imp.days_event_to_first_image > 15]
nm('latGoodLo', good.days_event_to_first_image.min(), '{:.1f}'); nm('latGoodHi', good.days_event_to_first_image.max(), '{:.0f}')
nm('latGoodRelLo', good.days_event_to_release.min(), '{:.0f}'); nm('latGoodRelHi', good.days_event_to_release.max(), '{:.0f}')
nm('latPoorLo', poor.days_event_to_first_image.min(), '{:.0f}'); nm('latPoorHi', poor.days_event_to_first_image.max(), '{:.0f}')
nm('latPoorRelLo', poor.days_event_to_release.min(), '{:.0f}'); nm('latPoorRelHi', poor.days_event_to_release.max(), '{:.0f}')
nm('latNimp', len(imp), '{:d}'); nm('latNctx', len(ol) - len(imp), '{:d}')
lro = orbcfg['lro']; nm('pLro', lro['p_operational_2028']); nm('pLroLo', lro['p_operational_sensitivity'][0]); nm('pLroHi', lro['p_operational_sensitivity'][1])
osj = json.load(open(need('outputs/tables/orbiter_seasons.json')))
def fmt_season(x):
    a_, b_ = pd.Timestamp(x[0]), pd.Timestamp(x[1])
    return f"{a_.day}~{a_.strftime('%B')}--{b_.day}~{b_.strftime('%B')}~{b_.year}" if a_.year == b_.year else f"{a_.day}~{a_.strftime('%B')}~{a_.year}--{b_.day}~{b_.strftime('%B')}~{b_.year}"
in_dom = lambda w: w['end'] >= dom['domain']['start_utc'][:10] and w['start'] < dom['domain']['stop_utc'][:10]
nm('lroSeasons', '; '.join(fmt_season((w['start'], w['end'])) for w in osj['lro']['low_sun'] if in_dom(w)))
nm('lroNoon', '; '.join(fmt_season((w['start'], w['end'])) for w in osj['lro']['near_noon'] if in_dom(w)))
hs = osj['lro']['holdout_summary']
nm('lroHoldShift', hs['central_fit_max_boundary_shift_days'], '{:.0f}'); nm('lroHoldNode', hs['central_fit_max_node_error_deg'], '{:.0f}')
nm('lroTrackEnd', osj['lro']['tracking_based_until_tdb'])
rng_days = [(pd.Timestamp(w[k][1]) - pd.Timestamp(w[k][0])).days for w in osj['lro']['low_sun'] if in_dom(w) for k in ('start_range', 'end_range')]
nm('lroRangeMax', max(rng_days), '{:d}')
rates = osj['lro']['node_rates_deg_per_day']
obs_r = [abs(v) for k, v in rates.items() if 'not used' not in k]; pred_r = [abs(v) for k, v in rates.items() if 'not used' in k]
nm('lroRateObsLo', min(obs_r), '{:.2f}'); nm('lroRateObsHi', max(obs_r), '{:.2f}'); nm('lroRatePredLo', min(pred_r), '{:.3f}'); nm('lroRatePredHi', max(pred_r), '{:.2f}')
chk = {c_['case']: c_ for c_ in osj['lro']['checks']}
nm('lroFalconInc', chk['Falcon 9 stage crater']['predicted_incidence_deg'], '{:.1f}'); nm('lroSlimInc', chk['SLIM landing site']['predicted_incidence_deg'], '{:.1f}')
dan = orbcfg['danuri']; nm('danP', dan['p_operational_before_planned_end'], '{:.1f}'); nm('danUntil', osj['danuri']['available_until'])
dsj = osj['danuri']
nm('danSeasons', '; '.join(fmt_season((w['start'], w['end'])) for w in dsj['low_sun'] if not w.get('after_planned_end') and w['end'] >= '2027-01-01'))
nm('danTrackEnd', dsj['tracking_based_until_tdb']); nm('danPredDiff', dsj['prediction_check']['max_abs_beta_difference_deg'], '{:.1f}')
d_rates = [abs(v) for k, v in dsj['node_rates_deg_per_day'].items() if 'not used' not in k]
nm('danRateLo', min(d_rates), '{:.3f}'); nm('danRateHi', max(d_rates), '{:.3f}')
nm('danBefore', listing([sid for sid in order if cards[sid]['orbiters']['danuri']['available_in_baseline']]))
lca = json.load(open(need('outputs/validation/lightcurve_accuracy.json')))
nm('lcAcc', '$' + sci(max(lca['worst_abs_dmag'].values()), 0) + '$')
gcp = f'{root}/outputs/validation/catalogue_gate_check.json'          # written by `make gatecheck` (not part of `make all`)
if os.path.exists(gcp):
    gc = json.load(open(gcp))
    nm('gcRows', thou(gc['rows'])); nm('gcMis', int(gc['total_count_mismatches']), '{:d}'); nm('gcMisTr', int(gc['turkish_count_mismatches']), '{:d}')
    nm('gcMargin', gc['max_threshold_margin_of_mismatched_rows_deg'] or 0.0, '{:.3f}'); nb_ = int(gc['rows_with_fewer_than_3_sites_but_stored_3_or_more'])
    nm('gcBelow', nb_, '{:d}')
    nm('gcBelowTxt', 'never takes a class-B entry below three sites' if nb_ == 0 else f'takes {nb_} class-B entr{"y" if nb_ == 1 else "ies"} below three sites')
else:
    print('WARNING: outputs/validation/catalogue_gate_check.json missing (run `make gatecheck`); its macros are set to ?')
    for k_ in ('gcRows', 'gcMis', 'gcMisTr', 'gcMargin', 'gcBelow', 'gcBelowTxt'):
        nm(k_, '?')
tc = json.load(open(need('outputs/validation/transfer_check.json')))['main']
nm('trOffset', tc['impact_before_overflight_s'], '{:.1f}'); nm('trFlight', tc['burn_to_impact_s'] / 60, '{:.1f}')
nm('trMiss', tc['max_miss_km'], '{:.2f}'); nm('trN', int(tc['n_checked']), '{:d}')
off50, tf50 = OP.transfer_offset_s(fam['altitude_km'], 50.0); nm('trOffsetFifty', off50, '{:.1f}'); nm('trFlightFifty', tf50 / 60, '{:.1f}')
# facility matrix
fm_ = pd.read_csv(need('outputs/tables/facility_site_time_matrix.csv'))
nm('matRows', len(fm_), '{:d}'); nm('matMaxSites', max(c['n_sites_available'] for c in cards.values()), '{:d}')
open(f'{SEC}/numbers.tex', 'w').write('\n'.join(NUM) + '\n')
print('tables written;', len(NUM) - 1, 'number macros')
