"""Regression tests for the reproduction checker (re-audit ST-23): `make test-checker`.

The archived outputs are copied twice into a scratch folder (.check/checker_test, hard links for files that are not
modified). The checker must PASS the copy against the original and FAIL each corruption used in the re-audit of
release 2.0: Monte Carlo CSV tables replaced by text, all S1 uncertainty intervals set to [0, 1], paired strategy
effects set to 999, injection m90/width/recovery fractions set to 999, the false-alarm arrays emptied, the dual
coincidence rate set to 999 and the website scenario list emptied; plus inverted outer quantiles. Prints one line per
case and writes .check/checker_test/report.md; exit status 0 only if every expectation holds.
outputs/screening/classes.npz is regenerated by every real run but deliberately not archived, so a fresh checkout does
not have it; the test leaves it out of both copies and does not require it, and gives the same result whether or not
the pipeline has been run in this folder."""
import sys, os, io, json, shutil, contextlib, importlib.util
root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
spec = importlib.util.spec_from_file_location('cr', os.path.join(root, 'scripts', 'check_reproduction.py'))
CR = importlib.util.module_from_spec(spec); spec.loader.exec_module(CR)
base = os.path.join(root, '.check', 'checker_test'); shutil.rmtree(base, ignore_errors=True); os.makedirs(base)

CR.REQUIRED = [f for f in CR.REQUIRED if f not in CR.UNARCHIVED]           # not archived: absent from a fresh checkout
UNARCHIVED_NAMES = {os.path.basename(f) for f in CR.UNARCHIVED}

def copy_tree(dst):
    for sub in ('outputs', os.path.join('site', 'data')):
        shutil.copytree(os.path.join(root, sub), os.path.join(dst, sub), copy_function=os.link,
                        ignore=lambda d, names: [n for n in names if n in UNARCHIVED_NAMES and os.path.relpath(os.path.join(d, n), root) in CR.UNARCHIVED])
    return dst

def rewrite(path, text):
    os.remove(path)                                             # break the hard link before writing
    open(path, 'w').write(text)

def edit_json(path, fn):
    d = json.load(open(path)); fn(d); rewrite(path, json.dumps(d))

def card_intervals(d):
    for m in d['mc'].values():
        for st in m['strategies'].values():
            for o in CR.OUTCOMES:
                st[o]['ci95'] = [0.0, 1.0]

def card_paired(d):
    for m in d['mc'].values():
        for v in m['paired'].values():
            v['diff'] = 999.0; v['ci95'] = [998.0, 1000.0]

def card_quantiles(d):
    for m in d['mc'].values():
        for st in m['strategies'].values():
            st['any']['outer_p05'], st['any']['outer_p95'] = 0.9, 0.1

def inj_999(d):
    for k, v in d.items():
        if k.startswith('_'):
            continue
        for f in v['fits'].values():
            f['m90'] = 999.0; f['width'] = 999.0
        for r in v['rows']:
            r['frac_cam0'] = 999.0

def inj_empty(d):
    for k, v in d.items():
        if not k.startswith('_'):
            v['false_alarms']['candidate_rate_per_box_frame'] = []; v['false_alarms']['box_frames_with_candidate'] = []

def inj_dual(d):
    d['nel']['false_alarms']['dual_coincidence_rate_per_box_frame']['rate'] = 999.0

CASES = {
    'Monte Carlo CSV tables replaced by text': lambda t: [rewrite(os.path.join(t, f), 'INVALID CSV PRODUCT\n') for f in CR.MC_TABLES],
    'all S1 uncertainty intervals set to [0, 1]': lambda t: edit_json(os.path.join(t, 'outputs/scenarios/S1.json'), card_intervals),
    'S1 paired strategy effects set to 999': lambda t: edit_json(os.path.join(t, 'outputs/scenarios/S1.json'), card_paired),
    'S1 outer quantiles inverted': lambda t: edit_json(os.path.join(t, 'outputs/scenarios/S1.json'), card_quantiles),
    'injection m90, width and recovery fractions set to 999': lambda t: edit_json(os.path.join(t, 'outputs/tables/injection_recovery.json'), inj_999),
    'injection false-alarm arrays emptied': lambda t: edit_json(os.path.join(t, 'outputs/tables/injection_recovery.json'), inj_empty),
    'dual-camera coincidence rate set to 999': lambda t: edit_json(os.path.join(t, 'outputs/tables/injection_recovery.json'), inj_dual),
    'website scenario list emptied': lambda t: rewrite(os.path.join(t, 'site/data/scenarios.json'), json.dumps({'scenarios': []})),
}

def run(ref, new):
    buf = io.StringIO()
    with contextlib.redirect_stdout(buf):
        rep = CR.compare(ref, new)
    return rep

ref = copy_tree(os.path.join(base, 'ref'))
lines = ['# Checker regression tests', '']
ok_all = True
rep = run(ref, copy_tree(os.path.join(base, 'same')))
good = not rep.fail
ok_all &= good
lines.append(f"- unmodified copy: {'PASS (expected PASS)' if good else 'FAIL (expected PASS)'}")
print(f"{'ok ' if good else 'BAD'} unmodified copy -> {'PASS' if not rep.fail else 'FAIL'}")
if rep.fail:
    print('\n'.join(rep.lines))
for name, fn in CASES.items():
    t = copy_tree(os.path.join(base, 'case'))
    fn(t)
    rep = run(ref, t)
    fails = [l for l in rep.lines if l.startswith('[FAIL]') and 'RESULT' not in l]
    good = rep.fail
    ok_all &= good
    lines.append(f"- {name}: {'FAIL as expected' if good else 'PASS (NOT DETECTED)'}; failing checks: " + '; '.join(f[7:60] for f in fails[:3]))
    print(f"{'ok ' if good else 'BAD'} {name} -> {'FAIL' if rep.fail else 'PASS'} ({len(fails)} failing checks)")
    shutil.rmtree(t)
open(os.path.join(base, 'report.md'), 'w').write('\n'.join(lines) + '\n')
print('ALL EXPECTATIONS MET' if ok_all else 'SOME EXPECTATIONS NOT MET'); sys.exit(0 if ok_all else 1)
